package io.github.lucasfcz.olympusprotocol;

import io.github.lucasfcz.olympusprotocol.dto.requests.ExerciseContraindicationRequest;
import io.github.lucasfcz.olympusprotocol.dto.requests.ExerciseRequest;
import io.github.lucasfcz.olympusprotocol.dto.requests.ExerciseTipRequest;
import io.github.lucasfcz.olympusprotocol.dto.requests.MuscleActivationRequest;
import io.github.lucasfcz.olympusprotocol.dto.requests.ReorderDaysRequest;
import io.github.lucasfcz.olympusprotocol.dto.requests.ReorderExercisesRequest;
import io.github.lucasfcz.olympusprotocol.dto.requests.UpdateWorkoutDayExerciseRequest;
import io.github.lucasfcz.olympusprotocol.dto.requests.UpdateWorkoutDayRequest;
import io.github.lucasfcz.olympusprotocol.dto.requests.WorkoutDayExerciseRequest;
import io.github.lucasfcz.olympusprotocol.dto.requests.WorkoutDayRequest;
import io.github.lucasfcz.olympusprotocol.dto.requests.WorkoutPlanRequest;
import io.github.lucasfcz.olympusprotocol.dto.responses.ExerciseContraindicationResponse;
import io.github.lucasfcz.olympusprotocol.dto.responses.ExerciseResponse;
import io.github.lucasfcz.olympusprotocol.dto.responses.ExerciseTipResponse;
import io.github.lucasfcz.olympusprotocol.dto.responses.MuscleActivationResponse;
import io.github.lucasfcz.olympusprotocol.models.*;
import io.github.lucasfcz.olympusprotocol.models.enums.*;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

/**
 * Fábrica centralizada de objetos para testes.
 * Todos os construtores espelham exatamente os das entidades reais.
 * Ao mudar um construtor de entidade, atualize aqui — o compilador vai avisar.
 */
public class TestFactory {

    // -------------------------------------------------------------------------
    // User
    // -------------------------------------------------------------------------

    public static User makeUser() {
        return new User(
                "Lucas Silva",
                "lucas@email.com",
                "hashed_password",
                ExperienceLevel.INTERMEDIATE,
                75.0,   // bodyWeight
                1.80    // height
        );
    }

    public static User makeUser(UUID id, ExperienceLevel experienceLevel) {
        User user = new User(
                "Test User " + id,
                "test" + id + "@email.com",
                "hashed_password",
                experienceLevel,
                75.0,
                1.80
        );
        // Using reflection or a setter to set the ID, as it's usually generated by the DB
        // For testing purposes, we can set it directly if the entity allows it or use reflection.
        // Assuming there's a way to set ID for testing. If not, this needs adjustment.
        try {
            java.lang.reflect.Field field = User.class.getDeclaredField("id");
            field.setAccessible(true);
            field.set(user, id);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException("Failed to set user ID for testing", e);
        }
        return user;
    }

    public static User makeUserWithoutBodyWeight() {
        return new User(
                "Lucas Silva",
                "lucas@email.com",
                "hashed_password",
                ExperienceLevel.INTERMEDIATE,
                null,   // bodyWeight ausente — caso de teste bodyweight
                1.80
        );
    }

    public static User makeBeginnerUser() {
        return new User(
                "Iniciante",
                "beginner@email.com",
                "hashed_password",
                ExperienceLevel.BEGINNER,
                70.0,
                1.75
        );
    }

    // -------------------------------------------------------------------------
    // Exercise
    // -------------------------------------------------------------------------

    public static Exercise makeExercise() {
        return new Exercise(
                "Supino Reto",
                "Exercício para peitoral",
                ExperienceLevel.BEGINNER,
                SafetyRating.SAFE,
                EfficiencyRating.HIGH,
                null,   // adminNotes
                null,   // gifUrl
                false   // usesBodyWeight
        );
    }

    public static Exercise makeExercise(ExperienceLevel recommendedExperienceLevel) {
        return new Exercise(
                "Supino Reto",
                "Exercício para peitoral",
                recommendedExperienceLevel,
                SafetyRating.SAFE,
                EfficiencyRating.HIGH,
                null,   // adminNotes
                null,   // gifUrl
                false   // usesBodyWeight
        );
    }

    public static Exercise makeExercise(UUID id, ExperienceLevel recommendedExperienceLevel) {
        return makeExercise(id, "Exercise " + id, recommendedExperienceLevel);
    }

    public static Exercise makeExercise(UUID id, String name, ExperienceLevel recommendedExperienceLevel) {
        Exercise exercise = new Exercise(
                name,
                "Description for " + name,
                recommendedExperienceLevel,
                SafetyRating.SAFE,
                EfficiencyRating.HIGH,
                null,
                null,
                false
        );
        try {
            java.lang.reflect.Field field = Exercise.class.getDeclaredField("id");
            field.setAccessible(true);
            field.set(exercise, id);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException("Failed to set exercise ID for testing", e);
        }
        return exercise;
    }

    public static Exercise makeBodyweightExercise() {
        return new Exercise(
                "Barra Fixa",
                "Exercício com peso corporal",
                ExperienceLevel.INTERMEDIATE,
                SafetyRating.SAFE,
                EfficiencyRating.HIGH,
                null,
                null,
                true    // usesBodyWeight
        );
    }

    public static Exercise makeAdvancedExercise() {
        return new Exercise(
                "Snatch",
                "Levantamento olímpico",
                ExperienceLevel.ADVANCED,
                SafetyRating.USE_WITH_CAUTION,
                EfficiencyRating.HIGH,
                null,
                null,
                false
        );
    }

    // -------------------------------------------------------------------------
    // WorkoutPlan / WorkoutDay / WorkoutDayExercise
    // -------------------------------------------------------------------------

    public static WorkoutPlan makeWorkoutPlan(User user) {
        return new WorkoutPlan(user, "Plano A - Força");
    }

    public static WorkoutPlan makePlan(User user) {
        return makePlan(UUID.randomUUID(), user);
    }

    public static WorkoutPlan makePlan(UUID id, User user) {
        WorkoutPlan plan = new WorkoutPlan(user, "Test Plan " + id);
        try {
            java.lang.reflect.Field field = WorkoutPlan.class.getDeclaredField("id");
            field.setAccessible(true);
            field.set(plan, id);
            java.lang.reflect.Field createdAtField = WorkoutPlan.class.getDeclaredField("createdAt");
            createdAtField.setAccessible(true);
            createdAtField.set(plan, LocalDateTime.now());
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException("Failed to set workout plan ID for testing", e);
        }
        return plan;
    }

    public static WorkoutDay makeWorkoutDay(WorkoutPlan plan) {
        return new WorkoutDay(plan, "Dia A - Peito e Tríceps", 1);
    }

    public static WorkoutDay makeWorkoutDay(UUID id, WorkoutPlan plan, String name, Integer dayOrder) {
        WorkoutDay day = new WorkoutDay(plan, name, dayOrder);
        try {
            java.lang.reflect.Field field = WorkoutDay.class.getDeclaredField("id");
            field.setAccessible(true);
            field.set(day, id);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException("Failed to set workout day ID for testing", e);
        }
        return day;
    }

    public static WorkoutDayExercise makeWorkoutDayExercise(WorkoutDay day, Exercise exercise) {
        return new WorkoutDayExercise(
                day,
                exercise,
                1,      // exerciseOrder
                4,      // sets
                10,     // reps
                60      // restTime (segundos)
        );
    }

    public static WorkoutDayExercise makeWorkoutDayExercise(UUID id, WorkoutDay day, Exercise exercise, Integer exerciseOrder) {
        WorkoutDayExercise wde = new WorkoutDayExercise(
                day,
                exercise,
                exerciseOrder,
                4,
                10,
                60
        );
        try {
            java.lang.reflect.Field field = WorkoutDayExercise.class.getDeclaredField("id");
            field.setAccessible(true);
            field.set(wde, id);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException("Failed to set workout day exercise ID for testing", e);
        }
        return wde;
    }

    // -------------------------------------------------------------------------
    // WorkoutSession
    // -------------------------------------------------------------------------

    public static WorkoutSession makeActiveSession(User user) {
        return new WorkoutSession(user, null); // sessão livre
    }

    public static WorkoutSession makeActiveSession(UUID id, User user) {
        WorkoutSession session = new WorkoutSession(user, null);
        try {
            java.lang.reflect.Field field = WorkoutSession.class.getDeclaredField("id");
            field.setAccessible(true);
            field.set(session, id);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException("Failed to set workout session ID for testing", e);
        }
        return session;
    }

    public static WorkoutSession makeActiveSession(User user, LocalDateTime startedAt) {
        WorkoutSession session = new WorkoutSession(user, null);
        try {
            java.lang.reflect.Field field = WorkoutSession.class.getDeclaredField("startedAt");
            field.setAccessible(true);
            field.set(session, startedAt);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException("Failed to set workout session startedAt for testing", e);
        }
        return session;
    }

    public static WorkoutSession makeActiveSessionFromDay(User user, WorkoutDay day) {
        return new WorkoutSession(user, day);
    }

    // -------------------------------------------------------------------------
    // WorkoutSessionExercise
    // -------------------------------------------------------------------------

    public static WorkoutSessionExercise makeSessionExercise(WorkoutSession session, Exercise exercise) {
        return new WorkoutSessionExercise(session, exercise, 1);
    }

    public static WorkoutSessionExercise makeSessionExercise(UUID id, WorkoutSession session, Exercise exercise) {
        WorkoutSessionExercise sessionExercise = new WorkoutSessionExercise(session, exercise, 1);
        try {
            java.lang.reflect.Field field = WorkoutSessionExercise.class.getDeclaredField("id");
            field.setAccessible(true);
            field.set(sessionExercise, id);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException("Failed to set workout session exercise ID for testing", e);
        }
        return sessionExercise;
    }

    // -------------------------------------------------------------------------
    // WorkoutSessionSet
    // -------------------------------------------------------------------------

    /** Set padrão com peso e reps */
    public static WorkoutSessionSet makeSet(WorkoutSessionExercise sessionExercise) {
        return new WorkoutSessionSet(
                sessionExercise,
                1,      // setOrder
                10,     // reps
                80.0,   // weight (kg)
                60,     // restTime (segundos)
                8.0     // rpe
        );
    }

    public static WorkoutSessionSet makeSet(UUID id, WorkoutSessionExercise sessionExercise) {
        WorkoutSessionSet set = new WorkoutSessionSet(
                sessionExercise,
                1,      // setOrder
                10,     // reps
                80.0,   // weight (kg)
                60,     // restTime (segundos)
                8.0     // rpe
        );
        try {
            java.lang.reflect.Field field = WorkoutSessionSet.class.getDeclaredField("id");
            field.setAccessible(true);
            field.set(set, id);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException("Failed to set workout session set ID for testing", e);
        }
        return set;
    }

    /** Set sem peso — para exercícios bodyweight antes de definir bodyWeight */
    public static WorkoutSessionSet makeSetWithoutWeight(WorkoutSessionExercise sessionExercise) {
        return new WorkoutSessionSet(
                sessionExercise,
                1,
                10,
                null,   // weight nulo
                60,
                null
        );
    }

    /** Set com peso específico — útil para testar PR e progressão */
    public static WorkoutSessionSet makeSetWithWeight(WorkoutSessionExercise sessionExercise,
                                                      int setOrder, int reps, double weight) {
        return new WorkoutSessionSet(
                sessionExercise,
                setOrder,
                reps,
                weight,
                60,
                null
        );
    }

    /** Monta uma sessão já finalizada com 1 exercício e 1 set */
    public static WorkoutSession makeFinishedSession(User user, Exercise exercise) {
        var session = makeActiveSession(user);
        var sessionExercise = makeSessionExercise(session, exercise);
        var set = makeSet(sessionExercise);
        sessionExercise.addSet(set);
        session.addExercise(sessionExercise);
        session.finish("Treino finalizado");
        return session;
    }

    // -------------------------------------------------------------------------
    // Request DTOs
    // -------------------------------------------------------------------------

    public static WorkoutPlanRequest samplePlanRequest() {
        return new WorkoutPlanRequest("My Workout Plan", WorkoutGoal.HYPERTROPHY);
    }

    public static WorkoutPlanRequest samplePlanRequest(String name) {
        return new WorkoutPlanRequest(name, WorkoutGoal.HYPERTROPHY);
    }

    public static WorkoutDayRequest sampleDayRequest() {
        return new WorkoutDayRequest("Leg Day", 1);
    }

    public static WorkoutDayExerciseRequest sampleDayExerciseRequest(UUID exerciseId) {
        return new WorkoutDayExerciseRequest(exerciseId, 1, 3, 10, 60);
    }

    public static UpdateWorkoutDayRequest sampleUpdateWorkoutDayRequest(String name, Integer dayOrder) {
        return new UpdateWorkoutDayRequest(name, dayOrder);
    }

    public static UpdateWorkoutDayExerciseRequest sampleUpdateWorkoutDayExerciseRequest(UUID exerciseId, Integer exerciseOrder, Integer sets, Integer reps, Integer restTime) {
        return new UpdateWorkoutDayExerciseRequest(exerciseId, exerciseOrder, sets, reps, restTime);
    }

    public static ReorderDaysRequest sampleReorderDaysRequest(List<ReorderDaysRequest.DayOrderItem> orders) {
        return new ReorderDaysRequest(orders);
    }

    public static ReorderExercisesRequest sampleReorderExercisesRequest(List<ReorderExercisesRequest.ExerciseOrderItem> orders) {
        return new ReorderExercisesRequest(orders);
    }

    public static MuscleActivationRequest makeMuscleActivationRequest() {
        return new MuscleActivationRequest(
                MuscleGroup.CHEST,
                MuscleRegion.UPPER,
                null,
                MuscleRole.TARGET,
                80
        );
    }

    public static ExerciseTipRequest makeExerciseTipRequest() {
        return new ExerciseTipRequest(
                ExperienceLevel.BEGINNER,
                TipType.FORM,
                "Keep your back straight."
        );
    }

    public static ExerciseContraindicationRequest makeExerciseContraindicationRequest() {
        return new ExerciseContraindicationRequest(
                "Shoulder pain",
                "Avoid if you have acute shoulder pain."
        );
    }

    public static ExerciseRequest sampleExerciseRequest() {
        return new ExerciseRequest(
                "Sample Exercise",
                "A sample exercise description",
                ExperienceLevel.BEGINNER,
                SafetyRating.SAFE,
                EfficiencyRating.HIGH,
                "Admin notes for sample exercise",
                "http://example.com/sample.gif",
                false,
                List.of(makeMuscleActivationRequest()),
                List.of(makeExerciseTipRequest()),
                List.of(makeExerciseContraindicationRequest())
        );
    }

    // -------------------------------------------------------------------------
    // Response DTOs
    // -------------------------------------------------------------------------

    public static MuscleActivationResponse makeMuscleActivationResponse(UUID id) {
        return new MuscleActivationResponse(
                id,
                MuscleGroup.CHEST,
                MuscleRegion.UPPER,
                null ,
                MuscleRole.TARGET,
                80
        );
    }

    public static ExerciseTipResponse makeExerciseTipResponse(UUID id) {
        return new ExerciseTipResponse(
                id,
                ExperienceLevel.BEGINNER,
                TipType.FORM,
                "Keep your back straight."
        );
    }

    public static ExerciseContraindicationResponse makeExerciseContraindicationResponse(UUID id) {
        return new ExerciseContraindicationResponse(
                id,
                "Shoulder pain",
                "Avoid if you have acute shoulder pain."
        );
    }

    public static ExerciseResponse makeExerciseResponse(UUID id) {
        return new ExerciseResponse(
                id,
                "Sample Exercise",
                "A sample exercise description",
                ExperienceLevel.BEGINNER,
                SafetyRating.SAFE,
                EfficiencyRating.HIGH,
                "Admin notes for sample exercise",
                "http://example.com/sample.gif",
                false,
                true, // active
                List.of(makeMuscleActivationResponse(UUID.randomUUID())),
                List.of(makeExerciseTipResponse(UUID.randomUUID())),
                List.of(makeExerciseContraindicationResponse(UUID.randomUUID()))
        );
    }
}