spring.application.name=olympus-protocol

server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_username}
spring.datasource.password=${DB_password}

#quando for para produção mudar para "spring.jpa.hibernate.ddl-auto=none"
spring.jpa.hibernate.ddl-auto=create-drop
spring.flyway.enabled=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.jwt.secret=${JWT_secret}
api.security.jwt.expiration=${JWT_EXPIRATION}